/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.xiaomi.miui.ad.appstore.feature;

import org.apache.commons.lang.builder.HashCodeBuilder;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.apache.thrift.*;
import org.apache.thrift.async.*;
import org.apache.thrift.meta_data.*;
import org.apache.thrift.transport.*;
import org.apache.thrift.protocol.*;

public class RankInstance implements TBase<RankInstance, RankInstance._Fields>, java.io.Serializable, Cloneable {
  private static final TStruct STRUCT_DESC = new TStruct("RankInstance");

  private static final TField DATA_FIELD_DESC = new TField("data", TType.STRUCT, (short)1);
  private static final TField APP_FIELD_DESC = new TField("app", TType.STRUCT, (short)2);
  private static final TField QUERY_EXTS_FIELD_DESC = new TField("queryExts", TType.LIST, (short)3);
  private static final TField QUERY_EXT_TF_IDF_FIELD_DESC = new TField("queryExtTfIdf", TType.LIST, (short)4);
  private static final TField QY_APP_LEVEL1_CATEGORY_NAME_FIELD_DESC = new TField("qyAppLevel1CategoryName", TType.LIST, (short)5);
  private static final TField QY_APP_LEVEL2_CATEGORY_NAME_FIELD_DESC = new TField("qyAppLevel2CategoryName", TType.LIST, (short)6);
  private static final TField QY_APP_TAGS_FIELD_DESC = new TField("qyAppTags", TType.LIST, (short)7);
  private static final TField QY_APP_IDS_FIELD_DESC = new TField("qyAppIds", TType.LIST, (short)8);
  private static final TField QY_KEYWORDS_FIELD_DESC = new TField("qyKeywords", TType.LIST, (short)9);
  private static final TField QY_RELATED_TAGS_FIELD_DESC = new TField("qyRelatedTags", TType.LIST, (short)10);
  private static final TField QY_FOLDER_TAGS_FIELD_DESC = new TField("qyFolderTags", TType.LIST, (short)11);
  private static final TField QY_SEARCH_KEYWORDS_FIELD_DESC = new TField("qySearchKeywords", TType.LIST, (short)12);
  private static final TField QY_DISPLAY_NAMES_FIELD_DESC = new TField("qyDisplayNames", TType.LIST, (short)13);
  private static final TField QY_PUBLISHER_FIELD_DESC = new TField("qyPublisher", TType.LIST, (short)14);
  private static final TField GOOGLE_CATES_FIELD_DESC = new TField("googleCates", TType.LIST, (short)15);

  private DataRaw data;
  private AppExt app;
  private List<QueryExtItem> queryExts;
  private List<String> queryExtTfIdf;
  private List<String> qyAppLevel1CategoryName;
  private List<String> qyAppLevel2CategoryName;
  private List<String> qyAppTags;
  private List<Long> qyAppIds;
  private List<String> qyKeywords;
  private List<String> qyRelatedTags;
  private List<String> qyFolderTags;
  private List<String> qySearchKeywords;
  private List<String> qyDisplayNames;
  private List<String> qyPublisher;
  private List<Integer> googleCates;

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements TFieldIdEnum {
    DATA((short)1, "data"),
    APP((short)2, "app"),
    QUERY_EXTS((short)3, "queryExts"),
    QUERY_EXT_TF_IDF((short)4, "queryExtTfIdf"),
    QY_APP_LEVEL1_CATEGORY_NAME((short)5, "qyAppLevel1CategoryName"),
    QY_APP_LEVEL2_CATEGORY_NAME((short)6, "qyAppLevel2CategoryName"),
    QY_APP_TAGS((short)7, "qyAppTags"),
    QY_APP_IDS((short)8, "qyAppIds"),
    QY_KEYWORDS((short)9, "qyKeywords"),
    QY_RELATED_TAGS((short)10, "qyRelatedTags"),
    QY_FOLDER_TAGS((short)11, "qyFolderTags"),
    QY_SEARCH_KEYWORDS((short)12, "qySearchKeywords"),
    QY_DISPLAY_NAMES((short)13, "qyDisplayNames"),
    QY_PUBLISHER((short)14, "qyPublisher"),
    GOOGLE_CATES((short)15, "googleCates");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // DATA
          return DATA;
        case 2: // APP
          return APP;
        case 3: // QUERY_EXTS
          return QUERY_EXTS;
        case 4: // QUERY_EXT_TF_IDF
          return QUERY_EXT_TF_IDF;
        case 5: // QY_APP_LEVEL1_CATEGORY_NAME
          return QY_APP_LEVEL1_CATEGORY_NAME;
        case 6: // QY_APP_LEVEL2_CATEGORY_NAME
          return QY_APP_LEVEL2_CATEGORY_NAME;
        case 7: // QY_APP_TAGS
          return QY_APP_TAGS;
        case 8: // QY_APP_IDS
          return QY_APP_IDS;
        case 9: // QY_KEYWORDS
          return QY_KEYWORDS;
        case 10: // QY_RELATED_TAGS
          return QY_RELATED_TAGS;
        case 11: // QY_FOLDER_TAGS
          return QY_FOLDER_TAGS;
        case 12: // QY_SEARCH_KEYWORDS
          return QY_SEARCH_KEYWORDS;
        case 13: // QY_DISPLAY_NAMES
          return QY_DISPLAY_NAMES;
        case 14: // QY_PUBLISHER
          return QY_PUBLISHER;
        case 15: // GOOGLE_CATES
          return GOOGLE_CATES;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments

  public static final Map<_Fields, FieldMetaData> metaDataMap;
  static {
    Map<_Fields, FieldMetaData> tmpMap = new EnumMap<_Fields, FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.DATA, new FieldMetaData("data", TFieldRequirementType.OPTIONAL, 
        new StructMetaData(TType.STRUCT, DataRaw.class)));
    tmpMap.put(_Fields.APP, new FieldMetaData("app", TFieldRequirementType.OPTIONAL, 
        new StructMetaData(TType.STRUCT, AppExt.class)));
    tmpMap.put(_Fields.QUERY_EXTS, new FieldMetaData("queryExts", TFieldRequirementType.OPTIONAL, 
        new ListMetaData(TType.LIST, 
            new StructMetaData(TType.STRUCT, QueryExtItem.class))));
    tmpMap.put(_Fields.QUERY_EXT_TF_IDF, new FieldMetaData("queryExtTfIdf", TFieldRequirementType.OPTIONAL, 
        new ListMetaData(TType.LIST, 
            new FieldValueMetaData(TType.STRING))));
    tmpMap.put(_Fields.QY_APP_LEVEL1_CATEGORY_NAME, new FieldMetaData("qyAppLevel1CategoryName", TFieldRequirementType.OPTIONAL, 
        new ListMetaData(TType.LIST, 
            new FieldValueMetaData(TType.STRING))));
    tmpMap.put(_Fields.QY_APP_LEVEL2_CATEGORY_NAME, new FieldMetaData("qyAppLevel2CategoryName", TFieldRequirementType.OPTIONAL, 
        new ListMetaData(TType.LIST, 
            new FieldValueMetaData(TType.STRING))));
    tmpMap.put(_Fields.QY_APP_TAGS, new FieldMetaData("qyAppTags", TFieldRequirementType.OPTIONAL, 
        new ListMetaData(TType.LIST, 
            new FieldValueMetaData(TType.STRING))));
    tmpMap.put(_Fields.QY_APP_IDS, new FieldMetaData("qyAppIds", TFieldRequirementType.OPTIONAL, 
        new ListMetaData(TType.LIST, 
            new FieldValueMetaData(TType.I64))));
    tmpMap.put(_Fields.QY_KEYWORDS, new FieldMetaData("qyKeywords", TFieldRequirementType.OPTIONAL, 
        new ListMetaData(TType.LIST, 
            new FieldValueMetaData(TType.STRING))));
    tmpMap.put(_Fields.QY_RELATED_TAGS, new FieldMetaData("qyRelatedTags", TFieldRequirementType.OPTIONAL, 
        new ListMetaData(TType.LIST, 
            new FieldValueMetaData(TType.STRING))));
    tmpMap.put(_Fields.QY_FOLDER_TAGS, new FieldMetaData("qyFolderTags", TFieldRequirementType.OPTIONAL, 
        new ListMetaData(TType.LIST, 
            new FieldValueMetaData(TType.STRING))));
    tmpMap.put(_Fields.QY_SEARCH_KEYWORDS, new FieldMetaData("qySearchKeywords", TFieldRequirementType.OPTIONAL, 
        new ListMetaData(TType.LIST, 
            new FieldValueMetaData(TType.STRING))));
    tmpMap.put(_Fields.QY_DISPLAY_NAMES, new FieldMetaData("qyDisplayNames", TFieldRequirementType.OPTIONAL, 
        new ListMetaData(TType.LIST, 
            new FieldValueMetaData(TType.STRING))));
    tmpMap.put(_Fields.QY_PUBLISHER, new FieldMetaData("qyPublisher", TFieldRequirementType.OPTIONAL, 
        new ListMetaData(TType.LIST, 
            new FieldValueMetaData(TType.STRING))));
    tmpMap.put(_Fields.GOOGLE_CATES, new FieldMetaData("googleCates", TFieldRequirementType.OPTIONAL, 
        new ListMetaData(TType.LIST, 
            new FieldValueMetaData(TType.I32))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    FieldMetaData.addStructMetaDataMap(RankInstance.class, metaDataMap);
  }

  public RankInstance() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public RankInstance(RankInstance other) {
    if (other.isSetData()) {
      this.data = new DataRaw(other.data);
    }
    if (other.isSetApp()) {
      this.app = new AppExt(other.app);
    }
    if (other.isSetQueryExts()) {
      List<QueryExtItem> __this__queryExts = new ArrayList<QueryExtItem>();
      for (QueryExtItem other_element : other.queryExts) {
        __this__queryExts.add(new QueryExtItem(other_element));
      }
      this.queryExts = __this__queryExts;
    }
    if (other.isSetQueryExtTfIdf()) {
      List<String> __this__queryExtTfIdf = new ArrayList<String>();
      for (String other_element : other.queryExtTfIdf) {
        __this__queryExtTfIdf.add(other_element);
      }
      this.queryExtTfIdf = __this__queryExtTfIdf;
    }
    if (other.isSetQyAppLevel1CategoryName()) {
      List<String> __this__qyAppLevel1CategoryName = new ArrayList<String>();
      for (String other_element : other.qyAppLevel1CategoryName) {
        __this__qyAppLevel1CategoryName.add(other_element);
      }
      this.qyAppLevel1CategoryName = __this__qyAppLevel1CategoryName;
    }
    if (other.isSetQyAppLevel2CategoryName()) {
      List<String> __this__qyAppLevel2CategoryName = new ArrayList<String>();
      for (String other_element : other.qyAppLevel2CategoryName) {
        __this__qyAppLevel2CategoryName.add(other_element);
      }
      this.qyAppLevel2CategoryName = __this__qyAppLevel2CategoryName;
    }
    if (other.isSetQyAppTags()) {
      List<String> __this__qyAppTags = new ArrayList<String>();
      for (String other_element : other.qyAppTags) {
        __this__qyAppTags.add(other_element);
      }
      this.qyAppTags = __this__qyAppTags;
    }
    if (other.isSetQyAppIds()) {
      List<Long> __this__qyAppIds = new ArrayList<Long>();
      for (Long other_element : other.qyAppIds) {
        __this__qyAppIds.add(other_element);
      }
      this.qyAppIds = __this__qyAppIds;
    }
    if (other.isSetQyKeywords()) {
      List<String> __this__qyKeywords = new ArrayList<String>();
      for (String other_element : other.qyKeywords) {
        __this__qyKeywords.add(other_element);
      }
      this.qyKeywords = __this__qyKeywords;
    }
    if (other.isSetQyRelatedTags()) {
      List<String> __this__qyRelatedTags = new ArrayList<String>();
      for (String other_element : other.qyRelatedTags) {
        __this__qyRelatedTags.add(other_element);
      }
      this.qyRelatedTags = __this__qyRelatedTags;
    }
    if (other.isSetQyFolderTags()) {
      List<String> __this__qyFolderTags = new ArrayList<String>();
      for (String other_element : other.qyFolderTags) {
        __this__qyFolderTags.add(other_element);
      }
      this.qyFolderTags = __this__qyFolderTags;
    }
    if (other.isSetQySearchKeywords()) {
      List<String> __this__qySearchKeywords = new ArrayList<String>();
      for (String other_element : other.qySearchKeywords) {
        __this__qySearchKeywords.add(other_element);
      }
      this.qySearchKeywords = __this__qySearchKeywords;
    }
    if (other.isSetQyDisplayNames()) {
      List<String> __this__qyDisplayNames = new ArrayList<String>();
      for (String other_element : other.qyDisplayNames) {
        __this__qyDisplayNames.add(other_element);
      }
      this.qyDisplayNames = __this__qyDisplayNames;
    }
    if (other.isSetQyPublisher()) {
      List<String> __this__qyPublisher = new ArrayList<String>();
      for (String other_element : other.qyPublisher) {
        __this__qyPublisher.add(other_element);
      }
      this.qyPublisher = __this__qyPublisher;
    }
    if (other.isSetGoogleCates()) {
      List<Integer> __this__googleCates = new ArrayList<Integer>();
      for (Integer other_element : other.googleCates) {
        __this__googleCates.add(other_element);
      }
      this.googleCates = __this__googleCates;
    }
  }

  public RankInstance deepCopy() {
    return new RankInstance(this);
  }

  @Override
  public void clear() {
    this.data = null;
    this.app = null;
    this.queryExts = null;
    this.queryExtTfIdf = null;
    this.qyAppLevel1CategoryName = null;
    this.qyAppLevel2CategoryName = null;
    this.qyAppTags = null;
    this.qyAppIds = null;
    this.qyKeywords = null;
    this.qyRelatedTags = null;
    this.qyFolderTags = null;
    this.qySearchKeywords = null;
    this.qyDisplayNames = null;
    this.qyPublisher = null;
    this.googleCates = null;
  }

  public DataRaw getData() {
    return this.data;
  }

  public RankInstance setData(DataRaw data) {
    this.data = data;
    return this;
  }

  public void unsetData() {
    this.data = null;
  }

  /** Returns true if field data is set (has been asigned a value) and false otherwise */
  public boolean isSetData() {
    return this.data != null;
  }

  public void setDataIsSet(boolean value) {
    if (!value) {
      this.data = null;
    }
  }

  public AppExt getApp() {
    return this.app;
  }

  public RankInstance setApp(AppExt app) {
    this.app = app;
    return this;
  }

  public void unsetApp() {
    this.app = null;
  }

  /** Returns true if field app is set (has been asigned a value) and false otherwise */
  public boolean isSetApp() {
    return this.app != null;
  }

  public void setAppIsSet(boolean value) {
    if (!value) {
      this.app = null;
    }
  }

  public int getQueryExtsSize() {
    return (this.queryExts == null) ? 0 : this.queryExts.size();
  }

  public java.util.Iterator<QueryExtItem> getQueryExtsIterator() {
    return (this.queryExts == null) ? null : this.queryExts.iterator();
  }

  public void addToQueryExts(QueryExtItem elem) {
    if (this.queryExts == null) {
      this.queryExts = new ArrayList<QueryExtItem>();
    }
    this.queryExts.add(elem);
  }

  public List<QueryExtItem> getQueryExts() {
    return this.queryExts;
  }

  public RankInstance setQueryExts(List<QueryExtItem> queryExts) {
    this.queryExts = queryExts;
    return this;
  }

  public void unsetQueryExts() {
    this.queryExts = null;
  }

  /** Returns true if field queryExts is set (has been asigned a value) and false otherwise */
  public boolean isSetQueryExts() {
    return this.queryExts != null;
  }

  public void setQueryExtsIsSet(boolean value) {
    if (!value) {
      this.queryExts = null;
    }
  }

  public int getQueryExtTfIdfSize() {
    return (this.queryExtTfIdf == null) ? 0 : this.queryExtTfIdf.size();
  }

  public java.util.Iterator<String> getQueryExtTfIdfIterator() {
    return (this.queryExtTfIdf == null) ? null : this.queryExtTfIdf.iterator();
  }

  public void addToQueryExtTfIdf(String elem) {
    if (this.queryExtTfIdf == null) {
      this.queryExtTfIdf = new ArrayList<String>();
    }
    this.queryExtTfIdf.add(elem);
  }

  public List<String> getQueryExtTfIdf() {
    return this.queryExtTfIdf;
  }

  public RankInstance setQueryExtTfIdf(List<String> queryExtTfIdf) {
    this.queryExtTfIdf = queryExtTfIdf;
    return this;
  }

  public void unsetQueryExtTfIdf() {
    this.queryExtTfIdf = null;
  }

  /** Returns true if field queryExtTfIdf is set (has been asigned a value) and false otherwise */
  public boolean isSetQueryExtTfIdf() {
    return this.queryExtTfIdf != null;
  }

  public void setQueryExtTfIdfIsSet(boolean value) {
    if (!value) {
      this.queryExtTfIdf = null;
    }
  }

  public int getQyAppLevel1CategoryNameSize() {
    return (this.qyAppLevel1CategoryName == null) ? 0 : this.qyAppLevel1CategoryName.size();
  }

  public java.util.Iterator<String> getQyAppLevel1CategoryNameIterator() {
    return (this.qyAppLevel1CategoryName == null) ? null : this.qyAppLevel1CategoryName.iterator();
  }

  public void addToQyAppLevel1CategoryName(String elem) {
    if (this.qyAppLevel1CategoryName == null) {
      this.qyAppLevel1CategoryName = new ArrayList<String>();
    }
    this.qyAppLevel1CategoryName.add(elem);
  }

  public List<String> getQyAppLevel1CategoryName() {
    return this.qyAppLevel1CategoryName;
  }

  public RankInstance setQyAppLevel1CategoryName(List<String> qyAppLevel1CategoryName) {
    this.qyAppLevel1CategoryName = qyAppLevel1CategoryName;
    return this;
  }

  public void unsetQyAppLevel1CategoryName() {
    this.qyAppLevel1CategoryName = null;
  }

  /** Returns true if field qyAppLevel1CategoryName is set (has been asigned a value) and false otherwise */
  public boolean isSetQyAppLevel1CategoryName() {
    return this.qyAppLevel1CategoryName != null;
  }

  public void setQyAppLevel1CategoryNameIsSet(boolean value) {
    if (!value) {
      this.qyAppLevel1CategoryName = null;
    }
  }

  public int getQyAppLevel2CategoryNameSize() {
    return (this.qyAppLevel2CategoryName == null) ? 0 : this.qyAppLevel2CategoryName.size();
  }

  public java.util.Iterator<String> getQyAppLevel2CategoryNameIterator() {
    return (this.qyAppLevel2CategoryName == null) ? null : this.qyAppLevel2CategoryName.iterator();
  }

  public void addToQyAppLevel2CategoryName(String elem) {
    if (this.qyAppLevel2CategoryName == null) {
      this.qyAppLevel2CategoryName = new ArrayList<String>();
    }
    this.qyAppLevel2CategoryName.add(elem);
  }

  public List<String> getQyAppLevel2CategoryName() {
    return this.qyAppLevel2CategoryName;
  }

  public RankInstance setQyAppLevel2CategoryName(List<String> qyAppLevel2CategoryName) {
    this.qyAppLevel2CategoryName = qyAppLevel2CategoryName;
    return this;
  }

  public void unsetQyAppLevel2CategoryName() {
    this.qyAppLevel2CategoryName = null;
  }

  /** Returns true if field qyAppLevel2CategoryName is set (has been asigned a value) and false otherwise */
  public boolean isSetQyAppLevel2CategoryName() {
    return this.qyAppLevel2CategoryName != null;
  }

  public void setQyAppLevel2CategoryNameIsSet(boolean value) {
    if (!value) {
      this.qyAppLevel2CategoryName = null;
    }
  }

  public int getQyAppTagsSize() {
    return (this.qyAppTags == null) ? 0 : this.qyAppTags.size();
  }

  public java.util.Iterator<String> getQyAppTagsIterator() {
    return (this.qyAppTags == null) ? null : this.qyAppTags.iterator();
  }

  public void addToQyAppTags(String elem) {
    if (this.qyAppTags == null) {
      this.qyAppTags = new ArrayList<String>();
    }
    this.qyAppTags.add(elem);
  }

  public List<String> getQyAppTags() {
    return this.qyAppTags;
  }

  public RankInstance setQyAppTags(List<String> qyAppTags) {
    this.qyAppTags = qyAppTags;
    return this;
  }

  public void unsetQyAppTags() {
    this.qyAppTags = null;
  }

  /** Returns true if field qyAppTags is set (has been asigned a value) and false otherwise */
  public boolean isSetQyAppTags() {
    return this.qyAppTags != null;
  }

  public void setQyAppTagsIsSet(boolean value) {
    if (!value) {
      this.qyAppTags = null;
    }
  }

  public int getQyAppIdsSize() {
    return (this.qyAppIds == null) ? 0 : this.qyAppIds.size();
  }

  public java.util.Iterator<Long> getQyAppIdsIterator() {
    return (this.qyAppIds == null) ? null : this.qyAppIds.iterator();
  }

  public void addToQyAppIds(long elem) {
    if (this.qyAppIds == null) {
      this.qyAppIds = new ArrayList<Long>();
    }
    this.qyAppIds.add(elem);
  }

  public List<Long> getQyAppIds() {
    return this.qyAppIds;
  }

  public RankInstance setQyAppIds(List<Long> qyAppIds) {
    this.qyAppIds = qyAppIds;
    return this;
  }

  public void unsetQyAppIds() {
    this.qyAppIds = null;
  }

  /** Returns true if field qyAppIds is set (has been asigned a value) and false otherwise */
  public boolean isSetQyAppIds() {
    return this.qyAppIds != null;
  }

  public void setQyAppIdsIsSet(boolean value) {
    if (!value) {
      this.qyAppIds = null;
    }
  }

  public int getQyKeywordsSize() {
    return (this.qyKeywords == null) ? 0 : this.qyKeywords.size();
  }

  public java.util.Iterator<String> getQyKeywordsIterator() {
    return (this.qyKeywords == null) ? null : this.qyKeywords.iterator();
  }

  public void addToQyKeywords(String elem) {
    if (this.qyKeywords == null) {
      this.qyKeywords = new ArrayList<String>();
    }
    this.qyKeywords.add(elem);
  }

  public List<String> getQyKeywords() {
    return this.qyKeywords;
  }

  public RankInstance setQyKeywords(List<String> qyKeywords) {
    this.qyKeywords = qyKeywords;
    return this;
  }

  public void unsetQyKeywords() {
    this.qyKeywords = null;
  }

  /** Returns true if field qyKeywords is set (has been asigned a value) and false otherwise */
  public boolean isSetQyKeywords() {
    return this.qyKeywords != null;
  }

  public void setQyKeywordsIsSet(boolean value) {
    if (!value) {
      this.qyKeywords = null;
    }
  }

  public int getQyRelatedTagsSize() {
    return (this.qyRelatedTags == null) ? 0 : this.qyRelatedTags.size();
  }

  public java.util.Iterator<String> getQyRelatedTagsIterator() {
    return (this.qyRelatedTags == null) ? null : this.qyRelatedTags.iterator();
  }

  public void addToQyRelatedTags(String elem) {
    if (this.qyRelatedTags == null) {
      this.qyRelatedTags = new ArrayList<String>();
    }
    this.qyRelatedTags.add(elem);
  }

  public List<String> getQyRelatedTags() {
    return this.qyRelatedTags;
  }

  public RankInstance setQyRelatedTags(List<String> qyRelatedTags) {
    this.qyRelatedTags = qyRelatedTags;
    return this;
  }

  public void unsetQyRelatedTags() {
    this.qyRelatedTags = null;
  }

  /** Returns true if field qyRelatedTags is set (has been asigned a value) and false otherwise */
  public boolean isSetQyRelatedTags() {
    return this.qyRelatedTags != null;
  }

  public void setQyRelatedTagsIsSet(boolean value) {
    if (!value) {
      this.qyRelatedTags = null;
    }
  }

  public int getQyFolderTagsSize() {
    return (this.qyFolderTags == null) ? 0 : this.qyFolderTags.size();
  }

  public java.util.Iterator<String> getQyFolderTagsIterator() {
    return (this.qyFolderTags == null) ? null : this.qyFolderTags.iterator();
  }

  public void addToQyFolderTags(String elem) {
    if (this.qyFolderTags == null) {
      this.qyFolderTags = new ArrayList<String>();
    }
    this.qyFolderTags.add(elem);
  }

  public List<String> getQyFolderTags() {
    return this.qyFolderTags;
  }

  public RankInstance setQyFolderTags(List<String> qyFolderTags) {
    this.qyFolderTags = qyFolderTags;
    return this;
  }

  public void unsetQyFolderTags() {
    this.qyFolderTags = null;
  }

  /** Returns true if field qyFolderTags is set (has been asigned a value) and false otherwise */
  public boolean isSetQyFolderTags() {
    return this.qyFolderTags != null;
  }

  public void setQyFolderTagsIsSet(boolean value) {
    if (!value) {
      this.qyFolderTags = null;
    }
  }

  public int getQySearchKeywordsSize() {
    return (this.qySearchKeywords == null) ? 0 : this.qySearchKeywords.size();
  }

  public java.util.Iterator<String> getQySearchKeywordsIterator() {
    return (this.qySearchKeywords == null) ? null : this.qySearchKeywords.iterator();
  }

  public void addToQySearchKeywords(String elem) {
    if (this.qySearchKeywords == null) {
      this.qySearchKeywords = new ArrayList<String>();
    }
    this.qySearchKeywords.add(elem);
  }

  public List<String> getQySearchKeywords() {
    return this.qySearchKeywords;
  }

  public RankInstance setQySearchKeywords(List<String> qySearchKeywords) {
    this.qySearchKeywords = qySearchKeywords;
    return this;
  }

  public void unsetQySearchKeywords() {
    this.qySearchKeywords = null;
  }

  /** Returns true if field qySearchKeywords is set (has been asigned a value) and false otherwise */
  public boolean isSetQySearchKeywords() {
    return this.qySearchKeywords != null;
  }

  public void setQySearchKeywordsIsSet(boolean value) {
    if (!value) {
      this.qySearchKeywords = null;
    }
  }

  public int getQyDisplayNamesSize() {
    return (this.qyDisplayNames == null) ? 0 : this.qyDisplayNames.size();
  }

  public java.util.Iterator<String> getQyDisplayNamesIterator() {
    return (this.qyDisplayNames == null) ? null : this.qyDisplayNames.iterator();
  }

  public void addToQyDisplayNames(String elem) {
    if (this.qyDisplayNames == null) {
      this.qyDisplayNames = new ArrayList<String>();
    }
    this.qyDisplayNames.add(elem);
  }

  public List<String> getQyDisplayNames() {
    return this.qyDisplayNames;
  }

  public RankInstance setQyDisplayNames(List<String> qyDisplayNames) {
    this.qyDisplayNames = qyDisplayNames;
    return this;
  }

  public void unsetQyDisplayNames() {
    this.qyDisplayNames = null;
  }

  /** Returns true if field qyDisplayNames is set (has been asigned a value) and false otherwise */
  public boolean isSetQyDisplayNames() {
    return this.qyDisplayNames != null;
  }

  public void setQyDisplayNamesIsSet(boolean value) {
    if (!value) {
      this.qyDisplayNames = null;
    }
  }

  public int getQyPublisherSize() {
    return (this.qyPublisher == null) ? 0 : this.qyPublisher.size();
  }

  public java.util.Iterator<String> getQyPublisherIterator() {
    return (this.qyPublisher == null) ? null : this.qyPublisher.iterator();
  }

  public void addToQyPublisher(String elem) {
    if (this.qyPublisher == null) {
      this.qyPublisher = new ArrayList<String>();
    }
    this.qyPublisher.add(elem);
  }

  public List<String> getQyPublisher() {
    return this.qyPublisher;
  }

  public RankInstance setQyPublisher(List<String> qyPublisher) {
    this.qyPublisher = qyPublisher;
    return this;
  }

  public void unsetQyPublisher() {
    this.qyPublisher = null;
  }

  /** Returns true if field qyPublisher is set (has been asigned a value) and false otherwise */
  public boolean isSetQyPublisher() {
    return this.qyPublisher != null;
  }

  public void setQyPublisherIsSet(boolean value) {
    if (!value) {
      this.qyPublisher = null;
    }
  }

  public int getGoogleCatesSize() {
    return (this.googleCates == null) ? 0 : this.googleCates.size();
  }

  public java.util.Iterator<Integer> getGoogleCatesIterator() {
    return (this.googleCates == null) ? null : this.googleCates.iterator();
  }

  public void addToGoogleCates(int elem) {
    if (this.googleCates == null) {
      this.googleCates = new ArrayList<Integer>();
    }
    this.googleCates.add(elem);
  }

  public List<Integer> getGoogleCates() {
    return this.googleCates;
  }

  public RankInstance setGoogleCates(List<Integer> googleCates) {
    this.googleCates = googleCates;
    return this;
  }

  public void unsetGoogleCates() {
    this.googleCates = null;
  }

  /** Returns true if field googleCates is set (has been asigned a value) and false otherwise */
  public boolean isSetGoogleCates() {
    return this.googleCates != null;
  }

  public void setGoogleCatesIsSet(boolean value) {
    if (!value) {
      this.googleCates = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case DATA:
      if (value == null) {
        unsetData();
      } else {
        setData((DataRaw)value);
      }
      break;

    case APP:
      if (value == null) {
        unsetApp();
      } else {
        setApp((AppExt)value);
      }
      break;

    case QUERY_EXTS:
      if (value == null) {
        unsetQueryExts();
      } else {
        setQueryExts((List<QueryExtItem>)value);
      }
      break;

    case QUERY_EXT_TF_IDF:
      if (value == null) {
        unsetQueryExtTfIdf();
      } else {
        setQueryExtTfIdf((List<String>)value);
      }
      break;

    case QY_APP_LEVEL1_CATEGORY_NAME:
      if (value == null) {
        unsetQyAppLevel1CategoryName();
      } else {
        setQyAppLevel1CategoryName((List<String>)value);
      }
      break;

    case QY_APP_LEVEL2_CATEGORY_NAME:
      if (value == null) {
        unsetQyAppLevel2CategoryName();
      } else {
        setQyAppLevel2CategoryName((List<String>)value);
      }
      break;

    case QY_APP_TAGS:
      if (value == null) {
        unsetQyAppTags();
      } else {
        setQyAppTags((List<String>)value);
      }
      break;

    case QY_APP_IDS:
      if (value == null) {
        unsetQyAppIds();
      } else {
        setQyAppIds((List<Long>)value);
      }
      break;

    case QY_KEYWORDS:
      if (value == null) {
        unsetQyKeywords();
      } else {
        setQyKeywords((List<String>)value);
      }
      break;

    case QY_RELATED_TAGS:
      if (value == null) {
        unsetQyRelatedTags();
      } else {
        setQyRelatedTags((List<String>)value);
      }
      break;

    case QY_FOLDER_TAGS:
      if (value == null) {
        unsetQyFolderTags();
      } else {
        setQyFolderTags((List<String>)value);
      }
      break;

    case QY_SEARCH_KEYWORDS:
      if (value == null) {
        unsetQySearchKeywords();
      } else {
        setQySearchKeywords((List<String>)value);
      }
      break;

    case QY_DISPLAY_NAMES:
      if (value == null) {
        unsetQyDisplayNames();
      } else {
        setQyDisplayNames((List<String>)value);
      }
      break;

    case QY_PUBLISHER:
      if (value == null) {
        unsetQyPublisher();
      } else {
        setQyPublisher((List<String>)value);
      }
      break;

    case GOOGLE_CATES:
      if (value == null) {
        unsetGoogleCates();
      } else {
        setGoogleCates((List<Integer>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case DATA:
      return getData();

    case APP:
      return getApp();

    case QUERY_EXTS:
      return getQueryExts();

    case QUERY_EXT_TF_IDF:
      return getQueryExtTfIdf();

    case QY_APP_LEVEL1_CATEGORY_NAME:
      return getQyAppLevel1CategoryName();

    case QY_APP_LEVEL2_CATEGORY_NAME:
      return getQyAppLevel2CategoryName();

    case QY_APP_TAGS:
      return getQyAppTags();

    case QY_APP_IDS:
      return getQyAppIds();

    case QY_KEYWORDS:
      return getQyKeywords();

    case QY_RELATED_TAGS:
      return getQyRelatedTags();

    case QY_FOLDER_TAGS:
      return getQyFolderTags();

    case QY_SEARCH_KEYWORDS:
      return getQySearchKeywords();

    case QY_DISPLAY_NAMES:
      return getQyDisplayNames();

    case QY_PUBLISHER:
      return getQyPublisher();

    case GOOGLE_CATES:
      return getGoogleCates();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been asigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case DATA:
      return isSetData();
    case APP:
      return isSetApp();
    case QUERY_EXTS:
      return isSetQueryExts();
    case QUERY_EXT_TF_IDF:
      return isSetQueryExtTfIdf();
    case QY_APP_LEVEL1_CATEGORY_NAME:
      return isSetQyAppLevel1CategoryName();
    case QY_APP_LEVEL2_CATEGORY_NAME:
      return isSetQyAppLevel2CategoryName();
    case QY_APP_TAGS:
      return isSetQyAppTags();
    case QY_APP_IDS:
      return isSetQyAppIds();
    case QY_KEYWORDS:
      return isSetQyKeywords();
    case QY_RELATED_TAGS:
      return isSetQyRelatedTags();
    case QY_FOLDER_TAGS:
      return isSetQyFolderTags();
    case QY_SEARCH_KEYWORDS:
      return isSetQySearchKeywords();
    case QY_DISPLAY_NAMES:
      return isSetQyDisplayNames();
    case QY_PUBLISHER:
      return isSetQyPublisher();
    case GOOGLE_CATES:
      return isSetGoogleCates();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof RankInstance)
      return this.equals((RankInstance)that);
    return false;
  }

  public boolean equals(RankInstance that) {
    if (that == null)
      return false;

    boolean this_present_data = true && this.isSetData();
    boolean that_present_data = true && that.isSetData();
    if (this_present_data || that_present_data) {
      if (!(this_present_data && that_present_data))
        return false;
      if (!this.data.equals(that.data))
        return false;
    }

    boolean this_present_app = true && this.isSetApp();
    boolean that_present_app = true && that.isSetApp();
    if (this_present_app || that_present_app) {
      if (!(this_present_app && that_present_app))
        return false;
      if (!this.app.equals(that.app))
        return false;
    }

    boolean this_present_queryExts = true && this.isSetQueryExts();
    boolean that_present_queryExts = true && that.isSetQueryExts();
    if (this_present_queryExts || that_present_queryExts) {
      if (!(this_present_queryExts && that_present_queryExts))
        return false;
      if (!this.queryExts.equals(that.queryExts))
        return false;
    }

    boolean this_present_queryExtTfIdf = true && this.isSetQueryExtTfIdf();
    boolean that_present_queryExtTfIdf = true && that.isSetQueryExtTfIdf();
    if (this_present_queryExtTfIdf || that_present_queryExtTfIdf) {
      if (!(this_present_queryExtTfIdf && that_present_queryExtTfIdf))
        return false;
      if (!this.queryExtTfIdf.equals(that.queryExtTfIdf))
        return false;
    }

    boolean this_present_qyAppLevel1CategoryName = true && this.isSetQyAppLevel1CategoryName();
    boolean that_present_qyAppLevel1CategoryName = true && that.isSetQyAppLevel1CategoryName();
    if (this_present_qyAppLevel1CategoryName || that_present_qyAppLevel1CategoryName) {
      if (!(this_present_qyAppLevel1CategoryName && that_present_qyAppLevel1CategoryName))
        return false;
      if (!this.qyAppLevel1CategoryName.equals(that.qyAppLevel1CategoryName))
        return false;
    }

    boolean this_present_qyAppLevel2CategoryName = true && this.isSetQyAppLevel2CategoryName();
    boolean that_present_qyAppLevel2CategoryName = true && that.isSetQyAppLevel2CategoryName();
    if (this_present_qyAppLevel2CategoryName || that_present_qyAppLevel2CategoryName) {
      if (!(this_present_qyAppLevel2CategoryName && that_present_qyAppLevel2CategoryName))
        return false;
      if (!this.qyAppLevel2CategoryName.equals(that.qyAppLevel2CategoryName))
        return false;
    }

    boolean this_present_qyAppTags = true && this.isSetQyAppTags();
    boolean that_present_qyAppTags = true && that.isSetQyAppTags();
    if (this_present_qyAppTags || that_present_qyAppTags) {
      if (!(this_present_qyAppTags && that_present_qyAppTags))
        return false;
      if (!this.qyAppTags.equals(that.qyAppTags))
        return false;
    }

    boolean this_present_qyAppIds = true && this.isSetQyAppIds();
    boolean that_present_qyAppIds = true && that.isSetQyAppIds();
    if (this_present_qyAppIds || that_present_qyAppIds) {
      if (!(this_present_qyAppIds && that_present_qyAppIds))
        return false;
      if (!this.qyAppIds.equals(that.qyAppIds))
        return false;
    }

    boolean this_present_qyKeywords = true && this.isSetQyKeywords();
    boolean that_present_qyKeywords = true && that.isSetQyKeywords();
    if (this_present_qyKeywords || that_present_qyKeywords) {
      if (!(this_present_qyKeywords && that_present_qyKeywords))
        return false;
      if (!this.qyKeywords.equals(that.qyKeywords))
        return false;
    }

    boolean this_present_qyRelatedTags = true && this.isSetQyRelatedTags();
    boolean that_present_qyRelatedTags = true && that.isSetQyRelatedTags();
    if (this_present_qyRelatedTags || that_present_qyRelatedTags) {
      if (!(this_present_qyRelatedTags && that_present_qyRelatedTags))
        return false;
      if (!this.qyRelatedTags.equals(that.qyRelatedTags))
        return false;
    }

    boolean this_present_qyFolderTags = true && this.isSetQyFolderTags();
    boolean that_present_qyFolderTags = true && that.isSetQyFolderTags();
    if (this_present_qyFolderTags || that_present_qyFolderTags) {
      if (!(this_present_qyFolderTags && that_present_qyFolderTags))
        return false;
      if (!this.qyFolderTags.equals(that.qyFolderTags))
        return false;
    }

    boolean this_present_qySearchKeywords = true && this.isSetQySearchKeywords();
    boolean that_present_qySearchKeywords = true && that.isSetQySearchKeywords();
    if (this_present_qySearchKeywords || that_present_qySearchKeywords) {
      if (!(this_present_qySearchKeywords && that_present_qySearchKeywords))
        return false;
      if (!this.qySearchKeywords.equals(that.qySearchKeywords))
        return false;
    }

    boolean this_present_qyDisplayNames = true && this.isSetQyDisplayNames();
    boolean that_present_qyDisplayNames = true && that.isSetQyDisplayNames();
    if (this_present_qyDisplayNames || that_present_qyDisplayNames) {
      if (!(this_present_qyDisplayNames && that_present_qyDisplayNames))
        return false;
      if (!this.qyDisplayNames.equals(that.qyDisplayNames))
        return false;
    }

    boolean this_present_qyPublisher = true && this.isSetQyPublisher();
    boolean that_present_qyPublisher = true && that.isSetQyPublisher();
    if (this_present_qyPublisher || that_present_qyPublisher) {
      if (!(this_present_qyPublisher && that_present_qyPublisher))
        return false;
      if (!this.qyPublisher.equals(that.qyPublisher))
        return false;
    }

    boolean this_present_googleCates = true && this.isSetGoogleCates();
    boolean that_present_googleCates = true && that.isSetGoogleCates();
    if (this_present_googleCates || that_present_googleCates) {
      if (!(this_present_googleCates && that_present_googleCates))
        return false;
      if (!this.googleCates.equals(that.googleCates))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    HashCodeBuilder builder = new HashCodeBuilder();

    boolean present_data = true && (isSetData());
    builder.append(present_data);
    if (present_data)
      builder.append(data);

    boolean present_app = true && (isSetApp());
    builder.append(present_app);
    if (present_app)
      builder.append(app);

    boolean present_queryExts = true && (isSetQueryExts());
    builder.append(present_queryExts);
    if (present_queryExts)
      builder.append(queryExts);

    boolean present_queryExtTfIdf = true && (isSetQueryExtTfIdf());
    builder.append(present_queryExtTfIdf);
    if (present_queryExtTfIdf)
      builder.append(queryExtTfIdf);

    boolean present_qyAppLevel1CategoryName = true && (isSetQyAppLevel1CategoryName());
    builder.append(present_qyAppLevel1CategoryName);
    if (present_qyAppLevel1CategoryName)
      builder.append(qyAppLevel1CategoryName);

    boolean present_qyAppLevel2CategoryName = true && (isSetQyAppLevel2CategoryName());
    builder.append(present_qyAppLevel2CategoryName);
    if (present_qyAppLevel2CategoryName)
      builder.append(qyAppLevel2CategoryName);

    boolean present_qyAppTags = true && (isSetQyAppTags());
    builder.append(present_qyAppTags);
    if (present_qyAppTags)
      builder.append(qyAppTags);

    boolean present_qyAppIds = true && (isSetQyAppIds());
    builder.append(present_qyAppIds);
    if (present_qyAppIds)
      builder.append(qyAppIds);

    boolean present_qyKeywords = true && (isSetQyKeywords());
    builder.append(present_qyKeywords);
    if (present_qyKeywords)
      builder.append(qyKeywords);

    boolean present_qyRelatedTags = true && (isSetQyRelatedTags());
    builder.append(present_qyRelatedTags);
    if (present_qyRelatedTags)
      builder.append(qyRelatedTags);

    boolean present_qyFolderTags = true && (isSetQyFolderTags());
    builder.append(present_qyFolderTags);
    if (present_qyFolderTags)
      builder.append(qyFolderTags);

    boolean present_qySearchKeywords = true && (isSetQySearchKeywords());
    builder.append(present_qySearchKeywords);
    if (present_qySearchKeywords)
      builder.append(qySearchKeywords);

    boolean present_qyDisplayNames = true && (isSetQyDisplayNames());
    builder.append(present_qyDisplayNames);
    if (present_qyDisplayNames)
      builder.append(qyDisplayNames);

    boolean present_qyPublisher = true && (isSetQyPublisher());
    builder.append(present_qyPublisher);
    if (present_qyPublisher)
      builder.append(qyPublisher);

    boolean present_googleCates = true && (isSetGoogleCates());
    builder.append(present_googleCates);
    if (present_googleCates)
      builder.append(googleCates);

    return builder.toHashCode();
  }

  public int compareTo(RankInstance other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    RankInstance typedOther = (RankInstance)other;

    lastComparison = Boolean.valueOf(isSetData()).compareTo(typedOther.isSetData());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetData()) {
      lastComparison = TBaseHelper.compareTo(this.data, typedOther.data);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetApp()).compareTo(typedOther.isSetApp());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetApp()) {
      lastComparison = TBaseHelper.compareTo(this.app, typedOther.app);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetQueryExts()).compareTo(typedOther.isSetQueryExts());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetQueryExts()) {
      lastComparison = TBaseHelper.compareTo(this.queryExts, typedOther.queryExts);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetQueryExtTfIdf()).compareTo(typedOther.isSetQueryExtTfIdf());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetQueryExtTfIdf()) {
      lastComparison = TBaseHelper.compareTo(this.queryExtTfIdf, typedOther.queryExtTfIdf);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetQyAppLevel1CategoryName()).compareTo(typedOther.isSetQyAppLevel1CategoryName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetQyAppLevel1CategoryName()) {
      lastComparison = TBaseHelper.compareTo(this.qyAppLevel1CategoryName, typedOther.qyAppLevel1CategoryName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetQyAppLevel2CategoryName()).compareTo(typedOther.isSetQyAppLevel2CategoryName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetQyAppLevel2CategoryName()) {
      lastComparison = TBaseHelper.compareTo(this.qyAppLevel2CategoryName, typedOther.qyAppLevel2CategoryName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetQyAppTags()).compareTo(typedOther.isSetQyAppTags());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetQyAppTags()) {
      lastComparison = TBaseHelper.compareTo(this.qyAppTags, typedOther.qyAppTags);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetQyAppIds()).compareTo(typedOther.isSetQyAppIds());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetQyAppIds()) {
      lastComparison = TBaseHelper.compareTo(this.qyAppIds, typedOther.qyAppIds);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetQyKeywords()).compareTo(typedOther.isSetQyKeywords());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetQyKeywords()) {
      lastComparison = TBaseHelper.compareTo(this.qyKeywords, typedOther.qyKeywords);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetQyRelatedTags()).compareTo(typedOther.isSetQyRelatedTags());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetQyRelatedTags()) {
      lastComparison = TBaseHelper.compareTo(this.qyRelatedTags, typedOther.qyRelatedTags);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetQyFolderTags()).compareTo(typedOther.isSetQyFolderTags());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetQyFolderTags()) {
      lastComparison = TBaseHelper.compareTo(this.qyFolderTags, typedOther.qyFolderTags);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetQySearchKeywords()).compareTo(typedOther.isSetQySearchKeywords());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetQySearchKeywords()) {
      lastComparison = TBaseHelper.compareTo(this.qySearchKeywords, typedOther.qySearchKeywords);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetQyDisplayNames()).compareTo(typedOther.isSetQyDisplayNames());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetQyDisplayNames()) {
      lastComparison = TBaseHelper.compareTo(this.qyDisplayNames, typedOther.qyDisplayNames);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetQyPublisher()).compareTo(typedOther.isSetQyPublisher());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetQyPublisher()) {
      lastComparison = TBaseHelper.compareTo(this.qyPublisher, typedOther.qyPublisher);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetGoogleCates()).compareTo(typedOther.isSetGoogleCates());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetGoogleCates()) {
      lastComparison = TBaseHelper.compareTo(this.googleCates, typedOther.googleCates);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(TProtocol iprot) throws TException {
    TField field;
    iprot.readStructBegin();
    while (true)
    {
      field = iprot.readFieldBegin();
      if (field.type == TType.STOP) { 
        break;
      }
      switch (field.id) {
        case 1: // DATA
          if (field.type == TType.STRUCT) {
            this.data = new DataRaw();
            this.data.read(iprot);
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 2: // APP
          if (field.type == TType.STRUCT) {
            this.app = new AppExt();
            this.app.read(iprot);
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 3: // QUERY_EXTS
          if (field.type == TType.LIST) {
            {
              TList _list124 = iprot.readListBegin();
              this.queryExts = new ArrayList<QueryExtItem>(_list124.size);
              for (int _i125 = 0; _i125 < _list124.size; ++_i125)
              {
                QueryExtItem _elem126;
                _elem126 = new QueryExtItem();
                _elem126.read(iprot);
                this.queryExts.add(_elem126);
              }
              iprot.readListEnd();
            }
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 4: // QUERY_EXT_TF_IDF
          if (field.type == TType.LIST) {
            {
              TList _list127 = iprot.readListBegin();
              this.queryExtTfIdf = new ArrayList<String>(_list127.size);
              for (int _i128 = 0; _i128 < _list127.size; ++_i128)
              {
                String _elem129;
                _elem129 = iprot.readString();
                this.queryExtTfIdf.add(_elem129);
              }
              iprot.readListEnd();
            }
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 5: // QY_APP_LEVEL1_CATEGORY_NAME
          if (field.type == TType.LIST) {
            {
              TList _list130 = iprot.readListBegin();
              this.qyAppLevel1CategoryName = new ArrayList<String>(_list130.size);
              for (int _i131 = 0; _i131 < _list130.size; ++_i131)
              {
                String _elem132;
                _elem132 = iprot.readString();
                this.qyAppLevel1CategoryName.add(_elem132);
              }
              iprot.readListEnd();
            }
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 6: // QY_APP_LEVEL2_CATEGORY_NAME
          if (field.type == TType.LIST) {
            {
              TList _list133 = iprot.readListBegin();
              this.qyAppLevel2CategoryName = new ArrayList<String>(_list133.size);
              for (int _i134 = 0; _i134 < _list133.size; ++_i134)
              {
                String _elem135;
                _elem135 = iprot.readString();
                this.qyAppLevel2CategoryName.add(_elem135);
              }
              iprot.readListEnd();
            }
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 7: // QY_APP_TAGS
          if (field.type == TType.LIST) {
            {
              TList _list136 = iprot.readListBegin();
              this.qyAppTags = new ArrayList<String>(_list136.size);
              for (int _i137 = 0; _i137 < _list136.size; ++_i137)
              {
                String _elem138;
                _elem138 = iprot.readString();
                this.qyAppTags.add(_elem138);
              }
              iprot.readListEnd();
            }
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 8: // QY_APP_IDS
          if (field.type == TType.LIST) {
            {
              TList _list139 = iprot.readListBegin();
              this.qyAppIds = new ArrayList<Long>(_list139.size);
              for (int _i140 = 0; _i140 < _list139.size; ++_i140)
              {
                long _elem141;
                _elem141 = iprot.readI64();
                this.qyAppIds.add(_elem141);
              }
              iprot.readListEnd();
            }
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 9: // QY_KEYWORDS
          if (field.type == TType.LIST) {
            {
              TList _list142 = iprot.readListBegin();
              this.qyKeywords = new ArrayList<String>(_list142.size);
              for (int _i143 = 0; _i143 < _list142.size; ++_i143)
              {
                String _elem144;
                _elem144 = iprot.readString();
                this.qyKeywords.add(_elem144);
              }
              iprot.readListEnd();
            }
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 10: // QY_RELATED_TAGS
          if (field.type == TType.LIST) {
            {
              TList _list145 = iprot.readListBegin();
              this.qyRelatedTags = new ArrayList<String>(_list145.size);
              for (int _i146 = 0; _i146 < _list145.size; ++_i146)
              {
                String _elem147;
                _elem147 = iprot.readString();
                this.qyRelatedTags.add(_elem147);
              }
              iprot.readListEnd();
            }
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 11: // QY_FOLDER_TAGS
          if (field.type == TType.LIST) {
            {
              TList _list148 = iprot.readListBegin();
              this.qyFolderTags = new ArrayList<String>(_list148.size);
              for (int _i149 = 0; _i149 < _list148.size; ++_i149)
              {
                String _elem150;
                _elem150 = iprot.readString();
                this.qyFolderTags.add(_elem150);
              }
              iprot.readListEnd();
            }
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 12: // QY_SEARCH_KEYWORDS
          if (field.type == TType.LIST) {
            {
              TList _list151 = iprot.readListBegin();
              this.qySearchKeywords = new ArrayList<String>(_list151.size);
              for (int _i152 = 0; _i152 < _list151.size; ++_i152)
              {
                String _elem153;
                _elem153 = iprot.readString();
                this.qySearchKeywords.add(_elem153);
              }
              iprot.readListEnd();
            }
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 13: // QY_DISPLAY_NAMES
          if (field.type == TType.LIST) {
            {
              TList _list154 = iprot.readListBegin();
              this.qyDisplayNames = new ArrayList<String>(_list154.size);
              for (int _i155 = 0; _i155 < _list154.size; ++_i155)
              {
                String _elem156;
                _elem156 = iprot.readString();
                this.qyDisplayNames.add(_elem156);
              }
              iprot.readListEnd();
            }
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 14: // QY_PUBLISHER
          if (field.type == TType.LIST) {
            {
              TList _list157 = iprot.readListBegin();
              this.qyPublisher = new ArrayList<String>(_list157.size);
              for (int _i158 = 0; _i158 < _list157.size; ++_i158)
              {
                String _elem159;
                _elem159 = iprot.readString();
                this.qyPublisher.add(_elem159);
              }
              iprot.readListEnd();
            }
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 15: // GOOGLE_CATES
          if (field.type == TType.LIST) {
            {
              TList _list160 = iprot.readListBegin();
              this.googleCates = new ArrayList<Integer>(_list160.size);
              for (int _i161 = 0; _i161 < _list160.size; ++_i161)
              {
                int _elem162;
                _elem162 = iprot.readI32();
                this.googleCates.add(_elem162);
              }
              iprot.readListEnd();
            }
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        default:
          TProtocolUtil.skip(iprot, field.type);
      }
      iprot.readFieldEnd();
    }
    iprot.readStructEnd();

    // check for required fields of primitive type, which can't be checked in the validate method
    validate();
  }

  public void write(TProtocol oprot) throws TException {
    validate();

    oprot.writeStructBegin(STRUCT_DESC);
    if (this.data != null) {
      if (isSetData()) {
        oprot.writeFieldBegin(DATA_FIELD_DESC);
        this.data.write(oprot);
        oprot.writeFieldEnd();
      }
    }
    if (this.app != null) {
      if (isSetApp()) {
        oprot.writeFieldBegin(APP_FIELD_DESC);
        this.app.write(oprot);
        oprot.writeFieldEnd();
      }
    }
    if (this.queryExts != null) {
      if (isSetQueryExts()) {
        oprot.writeFieldBegin(QUERY_EXTS_FIELD_DESC);
        {
          oprot.writeListBegin(new TList(TType.STRUCT, this.queryExts.size()));
          for (QueryExtItem _iter163 : this.queryExts)
          {
            _iter163.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
    }
    if (this.queryExtTfIdf != null) {
      if (isSetQueryExtTfIdf()) {
        oprot.writeFieldBegin(QUERY_EXT_TF_IDF_FIELD_DESC);
        {
          oprot.writeListBegin(new TList(TType.STRING, this.queryExtTfIdf.size()));
          for (String _iter164 : this.queryExtTfIdf)
          {
            oprot.writeString(_iter164);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
    }
    if (this.qyAppLevel1CategoryName != null) {
      if (isSetQyAppLevel1CategoryName()) {
        oprot.writeFieldBegin(QY_APP_LEVEL1_CATEGORY_NAME_FIELD_DESC);
        {
          oprot.writeListBegin(new TList(TType.STRING, this.qyAppLevel1CategoryName.size()));
          for (String _iter165 : this.qyAppLevel1CategoryName)
          {
            oprot.writeString(_iter165);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
    }
    if (this.qyAppLevel2CategoryName != null) {
      if (isSetQyAppLevel2CategoryName()) {
        oprot.writeFieldBegin(QY_APP_LEVEL2_CATEGORY_NAME_FIELD_DESC);
        {
          oprot.writeListBegin(new TList(TType.STRING, this.qyAppLevel2CategoryName.size()));
          for (String _iter166 : this.qyAppLevel2CategoryName)
          {
            oprot.writeString(_iter166);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
    }
    if (this.qyAppTags != null) {
      if (isSetQyAppTags()) {
        oprot.writeFieldBegin(QY_APP_TAGS_FIELD_DESC);
        {
          oprot.writeListBegin(new TList(TType.STRING, this.qyAppTags.size()));
          for (String _iter167 : this.qyAppTags)
          {
            oprot.writeString(_iter167);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
    }
    if (this.qyAppIds != null) {
      if (isSetQyAppIds()) {
        oprot.writeFieldBegin(QY_APP_IDS_FIELD_DESC);
        {
          oprot.writeListBegin(new TList(TType.I64, this.qyAppIds.size()));
          for (long _iter168 : this.qyAppIds)
          {
            oprot.writeI64(_iter168);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
    }
    if (this.qyKeywords != null) {
      if (isSetQyKeywords()) {
        oprot.writeFieldBegin(QY_KEYWORDS_FIELD_DESC);
        {
          oprot.writeListBegin(new TList(TType.STRING, this.qyKeywords.size()));
          for (String _iter169 : this.qyKeywords)
          {
            oprot.writeString(_iter169);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
    }
    if (this.qyRelatedTags != null) {
      if (isSetQyRelatedTags()) {
        oprot.writeFieldBegin(QY_RELATED_TAGS_FIELD_DESC);
        {
          oprot.writeListBegin(new TList(TType.STRING, this.qyRelatedTags.size()));
          for (String _iter170 : this.qyRelatedTags)
          {
            oprot.writeString(_iter170);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
    }
    if (this.qyFolderTags != null) {
      if (isSetQyFolderTags()) {
        oprot.writeFieldBegin(QY_FOLDER_TAGS_FIELD_DESC);
        {
          oprot.writeListBegin(new TList(TType.STRING, this.qyFolderTags.size()));
          for (String _iter171 : this.qyFolderTags)
          {
            oprot.writeString(_iter171);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
    }
    if (this.qySearchKeywords != null) {
      if (isSetQySearchKeywords()) {
        oprot.writeFieldBegin(QY_SEARCH_KEYWORDS_FIELD_DESC);
        {
          oprot.writeListBegin(new TList(TType.STRING, this.qySearchKeywords.size()));
          for (String _iter172 : this.qySearchKeywords)
          {
            oprot.writeString(_iter172);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
    }
    if (this.qyDisplayNames != null) {
      if (isSetQyDisplayNames()) {
        oprot.writeFieldBegin(QY_DISPLAY_NAMES_FIELD_DESC);
        {
          oprot.writeListBegin(new TList(TType.STRING, this.qyDisplayNames.size()));
          for (String _iter173 : this.qyDisplayNames)
          {
            oprot.writeString(_iter173);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
    }
    if (this.qyPublisher != null) {
      if (isSetQyPublisher()) {
        oprot.writeFieldBegin(QY_PUBLISHER_FIELD_DESC);
        {
          oprot.writeListBegin(new TList(TType.STRING, this.qyPublisher.size()));
          for (String _iter174 : this.qyPublisher)
          {
            oprot.writeString(_iter174);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
    }
    if (this.googleCates != null) {
      if (isSetGoogleCates()) {
        oprot.writeFieldBegin(GOOGLE_CATES_FIELD_DESC);
        {
          oprot.writeListBegin(new TList(TType.I32, this.googleCates.size()));
          for (int _iter175 : this.googleCates)
          {
            oprot.writeI32(_iter175);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
    }
    oprot.writeFieldStop();
    oprot.writeStructEnd();
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("RankInstance(");
    boolean first = true;

    if (isSetData()) {
      sb.append("data:");
      if (this.data == null) {
        sb.append("null");
      } else {
        sb.append(this.data);
      }
      first = false;
    }
    if (isSetApp()) {
      if (!first) sb.append(", ");
      sb.append("app:");
      if (this.app == null) {
        sb.append("null");
      } else {
        sb.append(this.app);
      }
      first = false;
    }
    if (isSetQueryExts()) {
      if (!first) sb.append(", ");
      sb.append("queryExts:");
      if (this.queryExts == null) {
        sb.append("null");
      } else {
        sb.append(this.queryExts);
      }
      first = false;
    }
    if (isSetQueryExtTfIdf()) {
      if (!first) sb.append(", ");
      sb.append("queryExtTfIdf:");
      if (this.queryExtTfIdf == null) {
        sb.append("null");
      } else {
        sb.append(this.queryExtTfIdf);
      }
      first = false;
    }
    if (isSetQyAppLevel1CategoryName()) {
      if (!first) sb.append(", ");
      sb.append("qyAppLevel1CategoryName:");
      if (this.qyAppLevel1CategoryName == null) {
        sb.append("null");
      } else {
        sb.append(this.qyAppLevel1CategoryName);
      }
      first = false;
    }
    if (isSetQyAppLevel2CategoryName()) {
      if (!first) sb.append(", ");
      sb.append("qyAppLevel2CategoryName:");
      if (this.qyAppLevel2CategoryName == null) {
        sb.append("null");
      } else {
        sb.append(this.qyAppLevel2CategoryName);
      }
      first = false;
    }
    if (isSetQyAppTags()) {
      if (!first) sb.append(", ");
      sb.append("qyAppTags:");
      if (this.qyAppTags == null) {
        sb.append("null");
      } else {
        sb.append(this.qyAppTags);
      }
      first = false;
    }
    if (isSetQyAppIds()) {
      if (!first) sb.append(", ");
      sb.append("qyAppIds:");
      if (this.qyAppIds == null) {
        sb.append("null");
      } else {
        sb.append(this.qyAppIds);
      }
      first = false;
    }
    if (isSetQyKeywords()) {
      if (!first) sb.append(", ");
      sb.append("qyKeywords:");
      if (this.qyKeywords == null) {
        sb.append("null");
      } else {
        sb.append(this.qyKeywords);
      }
      first = false;
    }
    if (isSetQyRelatedTags()) {
      if (!first) sb.append(", ");
      sb.append("qyRelatedTags:");
      if (this.qyRelatedTags == null) {
        sb.append("null");
      } else {
        sb.append(this.qyRelatedTags);
      }
      first = false;
    }
    if (isSetQyFolderTags()) {
      if (!first) sb.append(", ");
      sb.append("qyFolderTags:");
      if (this.qyFolderTags == null) {
        sb.append("null");
      } else {
        sb.append(this.qyFolderTags);
      }
      first = false;
    }
    if (isSetQySearchKeywords()) {
      if (!first) sb.append(", ");
      sb.append("qySearchKeywords:");
      if (this.qySearchKeywords == null) {
        sb.append("null");
      } else {
        sb.append(this.qySearchKeywords);
      }
      first = false;
    }
    if (isSetQyDisplayNames()) {
      if (!first) sb.append(", ");
      sb.append("qyDisplayNames:");
      if (this.qyDisplayNames == null) {
        sb.append("null");
      } else {
        sb.append(this.qyDisplayNames);
      }
      first = false;
    }
    if (isSetQyPublisher()) {
      if (!first) sb.append(", ");
      sb.append("qyPublisher:");
      if (this.qyPublisher == null) {
        sb.append("null");
      } else {
        sb.append(this.qyPublisher);
      }
      first = false;
    }
    if (isSetGoogleCates()) {
      if (!first) sb.append(", ");
      sb.append("googleCates:");
      if (this.googleCates == null) {
        sb.append("null");
      } else {
        sb.append(this.googleCates);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws TException {
    // check for required fields
  }

}

